name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed
    status:
      - success 

jobs:
  run-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull hrsuhas15/runtest:latest

      - name: Run Docker container
        run: docker run hrsuhas15/runtest:latest

      # Check the output score
      - name: Get output score
        id: check_score
        run: |
          OUTPUT=$(docker logs $(docker ps -lq))
          echo "::set-output name=score::$OUTPUT"
      
      - name: Check score
        run: |
          echo "Score:"
          echo "${{ steps.check_score.outputs.score }}"
          if [[ `echo "${{ steps.check_score.outputs.score }} 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi