name: Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t hrsuhas15/runtest:latest .

      - name: Push the Docker image
        run: docker push hrsuhas15/runtest:latest
  test:
    runs-on: ubuntu-latest
    needs: train
    if: success()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull hrsuhas15/runtest:latest

      - name: Run Docker container
        run: docker run hrsuhas15/runtest:latest

      - name: Get output score
        id: check_score
        run: |
          OUTPUT=$(docker logs $(docker ps -lq))
          echo "::set-output name=score::$OUTPUT"
      
      - name: Check score
        run: |
          echo "Score:"
          echo "${{ steps.check_score.outputs.score }}"
          if [[ `echo "${{ steps.check_score.outputs.score }} 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi